# stock
TIME_SERIES_KEY="Time Series"

FUNCTION_DAILY="DAILY"
FUNCTION_INTRADAY="INTRADAY"
FUNCTION_WEEKLY="WEEKLY"
FUNCTION_MONTHLY="MONTHLY"

FUNCTION_TIME_SERIES="TIME_SERIES"

# technical analysis
TA_KEY = "Technical Analysis"

INTERVAL_1MIN = '1min'
INTERVAL_5MIN = '5min'
INTERVAL_15MIN = '15min'
INTERVAL_30MIN = '30min'
INTERVAL_60MIN = '60min'
INTERVAL_DAILY = 'daily'
INTERVAL_WEEKLY = 'weekly'
INTERVAL_MONTHLY = 'monthly'